/**
 * Application error codes
 */
const ERROR_CODES = {
  INVALID_REQUEST: 'INVALID_REQUEST',
  SOURCE_NOT_FOUND: 'SOURCE_NOT_FOUND',
  SOURCE_DISABLED: 'SOURCE_DISABLED',
  CONVERSATION_NOT_FOUND: 'CONVERSATION_NOT_FOUND',
  INVALID_TURNSTILE_TOKEN: 'INVALID_TURNSTILE_TOKEN',
  INVALID_ORIGIN: 'INVALID_ORIGIN',
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  RATE_LIMITED: 'RATE_LIMITED',
  NOT_FOUND: 'NOT_FOUND',
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
} as const

type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES]

export { ERROR_CODES }
export type { ErrorCode }

